pagina_estatica:
    pattern: /{_locale}/sitio/{pagina}/
    defaults: { _controller: OfertaBundle:Sitio:estatica }
    requirements:
        _locale: en|es

portada:
    pattern: /{_locale}/{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada, ciudad: null }
    requirements:
        _locale: en|es

_portada:
    pattern: /
    defaults: { _controller: OfertaBundle:Default:portada }

# TODO: integrate plugin for real route translation (https://github.com/BeSimple/BeSimpleI18nRoutingBundle)


# BUNDLE ROUTES ###

UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/usuario
    requirements:
        _locale: en|es

TiendaBundle:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es

CiudadBundle:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es

OfertaBundle:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
