security:
    firewalls:
        frontend:
            # TODO: why route "usuario_login_check" throws an error?
            #pattern:    ^/
            anonymous:  ~
            switch_user: true
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                default_target_path: usuario_compras
                always_use_default_target_path: true
            logout:
                path: usuario_logout
            remember_me:
                key:      cupon1234
                lifetime: 3600

    access_control:
        - { path: ^/(es|en)/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/*, roles: ROLE_USUARIO }
        #- { path: ^/[a-z]{2}/usuario/*, roles: ROLE_USUARIO }

    providers:
        todos:
            providers: [usuarios, tiendas]
        usuarios:
            entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }
        tiendas:
            entity: { class: Cupon\TiendaBundle\Entity\Tienda, property: login }

    encoders:
        #Cupon\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }
        Cupon\UsuarioBundle\Entity\Usuario: plaintext
